name: Automatic lockfile update
on:
  schedule:
    - cron: '39 0 * * 6'
  workflow_dispatch:

jobs:
  # Update lockfile to reference latest nixpkgs/nixos-unstable commit.
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
      - uses: DeterminateSystems/nix-installer-action@main

      - uses: actions/checkout@v6

      - name: Update flake lockfile
        run: nix flake update

      - name: Send lockfile to next jobs
        uses: actions/upload-artifact@v7
        with:
          name: flake.lock
          path: flake.lock

  # Build the Breakout example from the Bevy repo on all supported systems.
  build-bevy-breakout:
    strategy:
      matrix:
        system: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]

    env:
      BEVY_VERSION: 0.19.0
      MACOS_SDK: ${{ secrets.MACOS_SDK }}
      TARGETS: |
        aarch64-unknown-linux-gnu
        x86_64-unknown-linux-gnu
        aarch64-pc-windows-msvc
        x86_64-pc-windows-msvc
        aarch64-apple-darwin
        x86_64-apple-darwin
        wasm32-unknown-unknown

    runs-on: ${{ matrix.system }}
    needs: [update-lockfile]

    # Use nixpkgs system names, instead of the ones that come with the runners.
    name: |-
      build-${{ case(
        matrix.system == 'ubuntu-latest', 'x86_64-linux',
        matrix.system == 'ubuntu-24.04-arm', 'aarch64-linux',
        matrix.system == 'macos-latest', 'aarch64-darwin',
        'unknown-system'
      ) }}

    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - uses: actions/checkout@v6
        with:
          path: bevy-flake

      - uses: actions/download-artifact@v8
        with:
          name: flake.lock
          path: bevy-flake

      - name: Clean lock in bevy-flake
        working-directory: bevy-flake
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add ./flake.lock
          git commit -m "Fetched updated lock." || true

      - name: Get bevy repo with lockfile from crates.io
        run: |
          curl -L -o download "https://static.crates.io/crates/bevy/bevy-$BEVY_VERSION.crate"
          tar -xf download
          rm download
          mv "bevy-$BEVY_VERSION" bevy

      - name: Add toolchian from 'fenix' template to runner
        working-directory: bevy
        run: |
          # Set pull flake template and lock it to new bevy-flake lockfile.
          nix flake init --template ../bevy-flake#fenix
          nix flake lock \
            --reference-lock-file ../bevy-flake/flake.lock \
            --override-input bevy-flake ../bevy-flake

          # Add MacOS SDK to config.
          awk '/fx.combine \(\[ fx.\${channel}.toolchain ] \+\+ stds);/ \
            { print; print "$MACOS_SDK"; next }1' flake.nix > flake.nix

          # Install toolchain on runner.
          nix profile add .#rust-toolchain

      - name: Build Breakout example for runner in dev environment
        working-directory: bevy
        run: |
          cargo build --example breakout
          cargo clean --profile dev

      - name: Build Breakout example for each supported target
        working-directory: bevy
        run: |
          for target in $TARGETS; do
            echo "::group::Build Breakout example for $target"

            cargo build --target "$target" --example breakout
            cargo clean --target "$target"

            echo "::endgroup::"
          done

  # Push lockfile if all supported systems build all targets successfully.
  push-lockfile:
    runs-on: ubuntu-latest
    needs: [update-lockfile, build-bevy-breakout]

    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: flake.lock

      - name: Push update lockfile
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add ./flake.lock
          git commit -m "Automatic lockfile update." || true
          git push origin main
