name: Automatic lockfile update
on:
  schedule:
    - cron: '39 0 * * 6'
  workflow_dispatch:

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    outputs:
      lockfile: ${{ steps.Output.outputs.lockfile }}

    steps:
      - uses: DeterminateSystems/nix-installer-action@main

      - uses: actions/checkout@v6

      - name: Update flake lockfile
        run: nix flake update

      - name: Send lockfile to next jobs
        uses: actions/upload-artifact@v7
        with:
          name: flake.lock
          path: flake.lock
  
  build-macos-aarch64:
    runs-on: macos-latest
    needs: update-lockfile
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - uses: actions/checkout@v6
        with:
          path: bevy-flake

      - uses: actions/download-artifact@v8
        with:
          name: flake.lock
          path: bevy-flake

      - uses: actions/checkout@v6
        with:
          repository: bevyengine/bevy
          ref: release-0.18.1
          path: bevy

      - name: Pull 'fenix' template, follow newly updated lockfile from bevy-flake
        working-directory: bevy
        run: |
          nix flake init --template ../bevy-flake#fenix
          nix flake lock \
            --reference-lock-file ../bevy-flake/flake.lock \
            --override-input bevy-flake ../bevy-flake \
            --allow-dirty-locks

      - name: Alias 'cargo' to run through Nix with pure env.
        working-directory: bevy
        run: |
          alias cargo="nix run --ignore-env .#rust-toolchain --"
          cargo

      # Build each target, cleaning afterwards to not exceed max storage usage.

      - name: Build Breakout example for runner in dev environment
        working-directory: bevy
        run: |
          cargo build --example breakout
          cargo clean --profile dev

      - name: Build Breakout example for aarch64-pc-windows-msvc
        working-directory: bevy
        run: |
          cargo build --example breakout --target aarch64-pc-windows-msvc
          cargo clean --target aarch64-pc-windows-msvc

      - name: Build Breakout example for x86_64-pc-windows-msvc
        working-directory: bevy
        run: |
          cargo build --example breakout --target x86_64-pc-windows-msvc
          cargo clean --target x86_64-pc-windows-msvc

      - name: Build Breakout example for aarch64-unknown-linux-gnu
        working-directory: bevy
        run: |
          cargo build --example breakout --target aarch64-unknown-linux-gnu
          cargo clean --target aarch64-unknown-linux-gnu

      - name: Build Breakout example for x86_64-unknown-linux-gnu
        working-directory: bevy
        run: |
          cargo build --example breakout --target x86_64-unknown-linux-gnu
          cargo clean --target x86_64-unknown-linux-gnu

      # Not building MacOS targets, as we have no SDK.
      
      # - name: Build Breakout example for aarch64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     cargo build --example breakout --target aarch64-apple-darwin
      #     cargo clean --target aarch64-apple-darwin

      # - name: Build Breakout example for x86_64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     cargo build --example breakout --target x86_64-apple-darwin
      #     cargo clean --target x86_64-apple-darwin

      - name: Build Breakout example for wasm32-unknown-unknown
        working-directory: bevy
        run: |
          cargo build --example breakout --target wasm32-unknown-unknown 
          cargo clean --target wasm32-unknown-unknown

  build-linux-x86_64:
    runs-on: ubuntu-latest
    needs: update-lockfile
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - uses: actions/checkout@v6
        with:
          path: bevy-flake

      - uses: actions/download-artifact@v8
        with:
          name: flake.lock
          path: bevy-flake
      
      - uses: actions/checkout@v6
        with:
          repository: bevyengine/bevy
          ref: release-0.18.1
          path: bevy

      - name: Pull 'fenix' template, follow newly updated lockfile from bevy-flake
        working-directory: bevy
        run: |
          nix flake init --template ../bevy-flake#fenix
          nix flake lock \
            --reference-lock-file ../bevy-flake/flake.lock \
            --override-input bevy-flake ../bevy-flake \
            --allow-dirty-locks

      - name: Alias 'cargo' to run through Nix with pure env.
        working-directory: bevy
        run: |
          alias cargo="nix run --ignore-env .#rust-toolchain --"
          cargo

      # Build each target, cleaning afterwards to not exceed max storage usage.

      - name: Build Breakout example for runner in dev environment
        working-directory: bevy
        run: |
          cargo build --example breakout
          cargo clean --profile dev

      - name: Build Breakout example for aarch64-pc-windows-msvc
        working-directory: bevy
        run: |
          cargo build --example breakout --target aarch64-pc-windows-msvc
          cargo clean --target aarch64-pc-windows-msvc

      - name: Build Breakout example for x86_64-pc-windows-msvc
        working-directory: bevy
        run: |
          cargo build --example breakout --target x86_64-pc-windows-msvc
          cargo clean --target x86_64-pc-windows-msvc

      - name: Build Breakout example for aarch64-unknown-linux-gnu
        working-directory: bevy
        run: |
          cargo build --example breakout --target aarch64-unknown-linux-gnu
          cargo clean --target aarch64-unknown-linux-gnu

      - name: Build Breakout example for x86_64-unknown-linux-gnu
        working-directory: bevy
        run: |
          cargo build --example breakout --target x86_64-unknown-linux-gnu
          cargo clean --target x86_64-unknown-linux-gnu

      # Not building MacOS targets, as we have no SDK.
      
      # - name: Build Breakout example for aarch64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     cargo build --example breakout --target aarch64-apple-darwin
      #     cargo clean --target aarch64-apple-darwin

      # - name: Build Breakout example for x86_64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     cargo build --example breakout --target x86_64-apple-darwin
      #     cargo clean --target x86_64-apple-darwin

      - name: Build Breakout example for wasm32-unknown-unknown
        working-directory: bevy
        run: |
          cargo build --example breakout --target wasm32-unknown-unknown 
          cargo clean --target wasm32-unknown-unknown

  build-linux-aarch64:
    runs-on: ubuntu-24.04-arm
    needs: update-lockfile
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - uses: actions/checkout@v6
        with:
          path: bevy-flake

      - uses: actions/download-artifact@v8
        with:
          name: flake.lock
          path: bevy-flake
      
      - uses: actions/checkout@v6
        with:
          repository: bevyengine/bevy
          ref: release-0.18.1
          path: bevy

      - name: Pull 'fenix' template, follow newly updated lockfile from bevy-flake
        working-directory: bevy
        run: |
          nix flake init --template ../bevy-flake#fenix
          nix flake lock \
            --reference-lock-file ../bevy-flake/flake.lock \
            --override-input bevy-flake ../bevy-flake \
            --allow-dirty-locks

      - name: Alias 'cargo' to run through Nix with pure env.
        working-directory: bevy
        run: |
          alias cargo="nix run --ignore-env .#rust-toolchain --"
          cargo

      # Build each target, cleaning afterwards to not exceed max storage usage.

      - name: Build Breakout example for runner in dev environment
        working-directory: bevy
        run: |
          cargo build --example breakout
          cargo clean --profile dev

      - name: Build Breakout example for aarch64-pc-windows-msvc
        working-directory: bevy
        run: |
          cargo build --example breakout --target aarch64-pc-windows-msvc
          cargo clean --target aarch64-pc-windows-msvc

      - name: Build Breakout example for x86_64-pc-windows-msvc
        working-directory: bevy
        run: |
          cargo build --example breakout --target x86_64-pc-windows-msvc
          cargo clean --target x86_64-pc-windows-msvc

      - name: Build Breakout example for aarch64-unknown-linux-gnu
        working-directory: bevy
        run: |
          cargo build --example breakout --target aarch64-unknown-linux-gnu
          cargo clean --target aarch64-unknown-linux-gnu

      - name: Build Breakout example for x86_64-unknown-linux-gnu
        working-directory: bevy
        run: |
          cargo build --example breakout --target x86_64-unknown-linux-gnu
          cargo clean --target x86_64-unknown-linux-gnu

      # Not building MacOS targets, as we have no SDK.
      
      # - name: Build Breakout example for aarch64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     cargo build --example breakout --target aarch64-apple-darwin
      #     cargo clean --target aarch64-apple-darwin

      # - name: Build Breakout example for x86_64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     cargo build --example breakout --target x86_64-apple-darwin
      #     cargo clean --target x86_64-apple-darwin

      - name: Build Breakout example for wasm32-unknown-unknown
        working-directory: bevy
        run: |
          cargo build --example breakout --target wasm32-unknown-unknown 
          cargo clean --target wasm32-unknown-unknown

  push-lockfile:
    runs-on: ubuntu-latest
    needs: [update-lockfile, build-macos-aarch64, build-linux-x86_64, build-linux-aarch64]

    # If every target builds successfully on both Linux and Macos, update is
    # good and we can push.
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: flake.lock

      - name: Push update lockfile
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add ./flake.lock
          git commit -m "Automatic lockfile update." | true
          git push origin main
