name: Automatic lockfile update
on:
  schedule:
    - cron: '39 0 * * 6'
  workflow_dispatch:

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    outputs:
      lockfile: ${{ steps.Output.outputs.lockfile }}

    steps:
      - uses: DeterminateSystems/nix-installer-action@main

      - uses: actions/checkout@v6

      - name: Update flake lockfile
        run: nix flake update

      - name: Send lockfile to next jobs
        uses: actions/upload-artifact@v7
        with:
          name: flake.lock
          path: flake.lock
  
  build-macos-aarch64:
    runs-on: macos-latest
    needs: update-lockfile
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - uses: actions/checkout@v6
        with:
          path: bevy-flake

      - uses: actions/download-artifact@v8
        with:
          name: flake.lock
          path: bevy-flake

      - name: Clean lock in bevy-flake
        working-directory: bevy-flake
        run: git add ./flake.lock

      - name: Get bevy repo with lockfile from crates.io
        run: |
          curl -L -o download https://static.crates.io/crates/bevy/bevy-0.18.1.crate
          tar -xf download
          rm download
          mv bevy-0.18.1 bevy
          rm bevy/.gitignore

      - name: Pull 'fenix' template, follow newly updated lockfile from bevy-flake
        working-directory: bevy
        run: |
          nix flake init --template ../bevy-flake#actions
          nix flake lock \
            --reference-lock-file ../bevy-flake/flake.lock \
            --override-input bevy-flake ../bevy-flake \
            --allow-dirty-locks

      - name: Set up bevy crate as git repo
        working-directory: bevy
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git init
          git add .
          git commit -m "Lets build!"

      - name: Build 'rust-toolchain' package.
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#rust-toolchain --no-link

      # Build each target, cleaning afterwards to not exceed max storage usage.

      # - name: Build Breakout example for runner in dev environment
      #   working-directory: bevy
      #   run: |
      #     nix flake show
      #     nix flake check
      #     nix run .#rust-toolchain build -- --example breakout
      #     nix run .#rust-toolchain clean -- --profile dev

      - name: Build Breakout example for aarch64-pc-windows-msvc
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#aarch64-unknown-pc-windows-msvc
          nix store delete ./result

      - name: Build Breakout example for x86_64-pc-windows-msvc
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#x86_64-unknown-pc-windows-msvc
          nix store delete ./result

      - name: Build Breakout example for aarch64-unknown-linux-gnu
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#aarch64-unknown-linux-gnu
          nix store delete ./result

      - name: Build Breakout example for x86_64-unknown-linux-gnu
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#x86_64-unknown-linux-gnu
          nix store delete ./result

      # Not building MacOS targets, as we have no SDK.
      
      # - name: Build Breakout example for aarch64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     nix build .#aarch64-apple-darwin
      #     nix store delete ./result

      # - name: Build Breakout example for x86_64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     nix build .#x86_64-apple-darwin
      #     nix store delete ./result

      - name: Build Breakout example for wasm32-unknown-unknown
        working-directory: bevy
        run: |
          nix flake show
          nix flake check

          nix build .#wasm32-unknown-unknown
          nix store delete ./result

  build-linux-x86_64:
    runs-on: ubuntu-latest
    needs: update-lockfile
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - uses: actions/checkout@v6
        with:
          path: bevy-flake

      - uses: actions/download-artifact@v8
        with:
          name: flake.lock
          path: bevy-flake

      - name: Clean lock in bevy-flake
        working-directory: bevy-flake
        run: git add ./flake.lock

      - name: Get bevy repo with lockfile from crates.io
        run: |
          curl -L -o download https://static.crates.io/crates/bevy/bevy-0.18.1.crate
          tar -xf download
          rm download
          mv bevy-0.18.1 bevy
          rm bevy/.gitignore

      - name: Pull 'fenix' template, follow newly updated lockfile from bevy-flake
        working-directory: bevy
        run: |
          nix flake init --template ../bevy-flake#actions
          nix flake lock \
            --reference-lock-file ../bevy-flake/flake.lock \
            --override-input bevy-flake ../bevy-flake \
            --allow-dirty-locks

      - name: Build 'rust-toolchain' package.
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#rust-toolchain --no-link

      # Build each target, cleaning afterwards to not exceed max storage usage.

      # - name: Build Breakout example for runner in dev environment
      #   working-directory: bevy
      #   run: |
      #     nix flake show
      #     nix flake check
      #     nix run .#rust-toolchain build -- --example breakout
      #     nix run .#rust-toolchain clean -- --profile dev

      - name: Build Breakout example for aarch64-pc-windows-msvc
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#aarch64-unknown-pc-windows-msvc
          nix store delete ./result

      - name: Build Breakout example for x86_64-pc-windows-msvc
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#x86_64-unknown-pc-windows-msvc
          nix store delete ./result

      - name: Build Breakout example for aarch64-unknown-linux-gnu
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#aarch64-unknown-linux-gnu
          nix store delete ./result

      - name: Build Breakout example for x86_64-unknown-linux-gnu
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#x86_64-unknown-linux-gnu
          nix store delete ./result

      # Not building MacOS targets, as we have no SDK.
      
      # - name: Build Breakout example for aarch64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     nix build .#aarch64-apple-darwin
      #     nix store delete ./result

      # - name: Build Breakout example for x86_64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     nix build .#x86_64-apple-darwin
      #     nix store delete ./result

      - name: Build Breakout example for wasm32-unknown-unknown
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#wasm32-unknown-unknown
          nix store delete ./result

  build-linux-aarch64:
    runs-on: ubuntu-24.04-arm
    needs: update-lockfile
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - uses: actions/checkout@v6
        with:
          path: bevy-flake

      - uses: actions/download-artifact@v8
        with:
          name: flake.lock
          path: bevy-flake

      - name: Clean lock in bevy-flake
        working-directory: bevy-flake
        run: git add ./flake.lock

      - name: Get bevy repo with lockfile from crates.io
        run: |
          curl -L -o download https://static.crates.io/crates/bevy/bevy-0.18.1.crate
          tar -xf download
          rm download
          mv bevy-0.18.1 bevy
          rm bevy/.gitignore

      - name: Pull 'fenix' template, follow newly updated lockfile from bevy-flake
        working-directory: bevy
        run: |
          nix flake init --template ../bevy-flake#actions
          nix flake lock \
            --reference-lock-file ../bevy-flake/flake.lock \
            --override-input bevy-flake ../bevy-flake \
            --allow-dirty-locks

      - name: Build 'rust-toolchain' package.
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#rust-toolchain --no-link

      # Build each target, cleaning afterwards to not exceed max storage usage.

      # - name: Build Breakout example for runner in dev environment
      #   working-directory: bevy
      #   run: |
      #     nix flake show
      #     nix flake check
      #     nix run .#rust-toolchain build -- --example breakout
      #     nix run .#rust-toolchain clean -- --profile dev

      - name: Build Breakout example for aarch64-pc-windows-msvc
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#aarch64-unknown-pc-windows-msvc
          nix store delete ./result

      - name: Build Breakout example for x86_64-pc-windows-msvc
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#x86_64-unknown-pc-windows-msvc
          nix store delete ./result

      - name: Build Breakout example for aarch64-unknown-linux-gnu
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#aarch64-unknown-linux-gnu
          nix store delete ./result

      - name: Build Breakout example for x86_64-unknown-linux-gnu
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#x86_64-unknown-linux-gnu
          nix store delete ./result

      # Not building MacOS targets, as we have no SDK.
      
      # - name: Build Breakout example for aarch64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     nix build .#aarch64-apple-darwin
      #     nix store delete ./result

      # - name: Build Breakout example for x86_64-apple-darwin
      #   working-directory: bevy
      #   run: |
      #     nix build .#x86_64-apple-darwin
      #     nix store delete ./result

      - name: Build Breakout example for wasm32-unknown-unknown
        working-directory: bevy
        run: |
          nix flake show
          nix flake check
          nix build .#wasm32-unknown-unknown
          nix store delete ./result

  push-lockfile:
    runs-on: ubuntu-latest
    needs: [update-lockfile, build-macos-aarch64, build-linux-x86_64, build-linux-aarch64]

    # If every target builds successfully on both Linux and Macos, update is
    # good and we can push.
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: flake.lock

      - name: Push update lockfile
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add ./flake.lock
          git commit -m "Automatic lockfile update." | true
          git push origin main
